### PR TITLE
add Unity.gitattributes

### PR DESCRIPTION
**Pull request by Neargye**

### CODE REVIEW

**Comment by ZhengzhongSun** [comment]
I think the previous version is better. Git lfs is more useful for most unity projects, this pull request shouldn't be merged.

**Comment by Richienb** [comment]
@ZhengzhongSun The only problem here is that Git LFS does not ship with Git and the external Git hosting provider needs to support it.

**Comment by ZhengzhongSun** [comment]
OK. This should be more general. Is it better to add the Git LFS part to comment in the Unity.gitattributes? So the people who need it can easily uncomment them and use it.

**Comment by Richienb** [comment]
@ZhengzhongSun Since it would essentially double the file size in order to add commented code, I'll just add instructions to the file.

**Comment by Richienb** [comment]
@ZhengzhongSun Fixed in https://github.com/alexkaratarakis/gitattributes/commit/29e644640454f1fab454a5fcd5c5a40e3e90aee5.

**Comment by ZhengzhongSun** [comment]
@Richienb  OK. But I usually see it should be "filter=lfs diff=lfs merge=lfs -text". I'm not sure if it will have problems only use diff=lfs merge=lfs.

**Comment by Richienb** [comment]
@ZhengzhongSun `-text` is part of a shorthand for `binary`. It should be fine.

**Pull request merged**
