### PR TITLE
Additional files

### PR DESCRIPTION
**Pull request by ceefour**
Additional files

### CODE REVIEW

**Comment by alexkaratarakis** [comment]
I must have missed this somehow. Added.

**Comment by bbodenmiller** [comment]
@Danimoth this PR introduces duplicate items between `Common.gitattributes` and the subject specific templates which we previously retried to remove (in for example https://github.com/Danimoth/gitattributes/commit/9c847499754e26e62099f1402de30481fd0ece6f).

**Comment by alexkaratarakis** [comment]
Fixed. Thanks Ben :+1: !
Do you think I should also move *.txt to Common?

**Comment by ceefour** [comment]
Pardon me. But may I know what was the reasoning behind strict splitting of
files?

Something like *.txt is "common", as the name suggested, but I'd argue that
exactly due to its generality, it belongs in all project types.

Does *.css and *.js belong in Web or PHP? I'd argue for both. Since 99% of
typical PHP projects would include both files.

In my opinion, it's much easier to just grab a file then remove the lines
that you don't want, than merging 3 files into a single .gitattributes
every time you want to start a project.

**Comment by alexkaratarakis** [comment]
Well there is two ways this can be done:
1) Remove the Common file altogether, and put a copy of it in every file. This would imply that every time a "common"  attribute is added, all files should be changed. On the plus side though, everyone can just grab the gitattribute file depending on his project. 

2) Have the Common file like now. The downside being, you have to manually merge on every project, as you mention. This is similar to what .gitignore project is doing atm: they have separate files for (e.g.) Java, Linux, Eclipse, so you must grab all 3 if that is your setup. 

Honestly, I am not sure which way would be best.  Although atm the first option seems like a good idea, I feel this will eventually go the .gitignore project way.

**Comment by ceefour** [comment]
It's possible to get convenience in both cases by having a "build script",
similar in how you guys minimize js for example, but much simpler. (Since
it's just file concatenation, only built in cat command is needed)

However, I suspect that editing .gitattributes files is very seldom
operation here anyway, that even manually editing multiple files once is an
effort simple enough it's worth it.

For principle, in DB world, if you write few and read many, then you should
optimize for read. This gitattributes repository is probably written once a
month and read thousands of times during that time. So I definitely on the
side of more convenience to the reader/user than the editor.

**Pull request merged**
