### PR TITLE
added cpi source file to C++ gitattributes

### PR DESCRIPTION
**Pull request by tsukinoko-kun**

### CODE REVIEW

**Comment by Richienb** [comment]
What is cpi?

**Comment by tsukinoko-kun** [comment]
> What is cpi?

cpi is used in older C++ projects (at the time of MFC). I have some of them at work. It's a regular C++ code file and as far as I can tell, they're nothing "special".

**Comment by alexkaratarakis** [comment]
It seems rare/old, but I managed to find a reference to it:
https://stackoverflow.com/questions/12682107/how-to-create-c-project-filter-folder-in-visual-studio

I think it wouldn't hurt to have it.

**Comment by alexkaratarakis** [comment]
Thank you!

**Pull request merged**
